
vscode:
  extensions:
    - ritwickdey.liveserver
    - github.vscode-pull-request-github
    - eamodio.gitlens
    - muhammad-sammy.csharp
image:
  file: .gitpod.Dockerfile

tasks:
  - name: Restore & Build
    init: |
      dotnet dev-certs https 
      dotnet restore
      dotnet build